modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="thickskullneoforge"
version="1.0.0"
displayName="ThickSkullNeoForge"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "thickskullneoforge.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.thickskullneoforge]]
    modId="neoforge"
    type="required"
    versionRange="[21.8.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.thickskullneoforge]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration